/**
 * Database schema migrations for Private Notes app
 * Each migration should be a single SQL statement
 */

/**
 * v001: Create notes table - absolute minimum for testing
 */
const V001_CREATE_NOTES_TABLE = `
CREATE TABLE IF NOT EXISTS notes (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  issue_key VARCHAR(255) NOT NULL,
  title VARCHAR(500) NOT NULL
)`;

/**
 * v002: Create note_permissions table - absolute minimum for testing
 */
const V002_CREATE_NOTE_PERMISSIONS_TABLE = `
CREATE TABLE IF NOT EXISTS note_permissions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  note_id BIGINT NOT NULL,
  user_account_id VARCHAR(128) NOT NULL
)`;

/**
 * v003: Create notifications table - absolute minimum for testing
 */
const V003_CREATE_NOTIFICATIONS_TABLE = `
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_account_id VARCHAR(128) NOT NULL,
  type VARCHAR(50) NOT NULL
)`;

/**
 * v004: Add missing columns to notes table
 */
const V004_ALTER_NOTES_ADD_COLUMNS = `
ALTER TABLE notes
ADD COLUMN IF NOT EXISTS content TEXT,
ADD COLUMN IF NOT EXISTS created_by VARCHAR(128),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS deadline TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'open'`;

/**
 * v005: Add missing columns to note_permissions table
 */
const V005_ALTER_PERMISSIONS_ADD_COLUMNS = `
ALTER TABLE note_permissions
ADD COLUMN IF NOT EXISTS permission_type VARCHAR(50) DEFAULT 'read',
ADD COLUMN IF NOT EXISTS granted_by VARCHAR(128),
ADD COLUMN IF NOT EXISTS granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP`;

/**
 * v006: Add missing columns to notifications table
 */
const V006_ALTER_NOTIFICATIONS_ADD_COLUMNS = `
ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS note_id BIGINT,
ADD COLUMN IF NOT EXISTS title VARCHAR(500),
ADD COLUMN IF NOT EXISTS message TEXT,
ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP`;

module.exports = {
  V001_CREATE_NOTES_TABLE,
  V002_CREATE_NOTE_PERMISSIONS_TABLE,
  V003_CREATE_NOTIFICATIONS_TABLE,
  V004_ALTER_NOTES_ADD_COLUMNS,
  V005_ALTER_PERMISSIONS_ADD_COLUMNS,
  V006_ALTER_NOTIFICATIONS_ADD_COLUMNS
};